import Link from "next/link";
import Image from "next/image";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import PublicScanInput from "./_components/PublicScanInput";

const DETECTORS: Array<{
  id: string;
  name: string;
  desc: string;
  refs: string;
}> = [
  {
    id: "01",
    name: "secret-scanner",
    desc: "60+ high-confidence patterns: AWS, GCP, Anthropic, OpenAI, Stripe, Slack, GitHub PATs, SSH keys, Supabase service-role JWTs.",
    refs: "regex",
  },
  {
    id: "02",
    name: "sensitive-files",
    desc: "Flags filenames that imply secrets regardless of content: .env.production, id_rsa, terraform.tfstate, kubeconfig, .npmrc.",
    refs: "filename only",
  },
  {
    id: "03",
    name: "entropy",
    desc: "Catches custom-format secrets in .env / config files via Shannon entropy on KEY=VALUE pairs. Skips placeholders automatically.",
    refs: "≥ 4.0 bits/char",
  },
  {
    id: "04",
    name: "git-history",
    desc: "Replays the last 30 commits looking for secrets that were deleted but never rotated. Dedups against the current tree.",
    refs: "30 commits",
  },
  {
    id: "05",
    name: "code-sast",
    desc: "AST-based via the TypeScript Compiler API plus targeted regex. 28 AST rules covering most of the OWASP Top 10 — SSRF, SQLi, command injection, reflected XSS, prototype pollution, ReDoS, NoSQL / SSTI injection, XXE, weak crypto, JWT misuse, hardcoded creds — plus AI-typical mistakes (TLS verify off, NEXT_PUBLIC_ secrets, bcrypt rounds < 10). Every rule CWE-tagged.",
    refs: "AST + regex · CWE-tagged",
  },
  {
    id: "06",
    name: "deps",
    desc: "npm package-lock.json against the npm advisories bulk API; PyPI requirements/pyproject/Pipfile against OSV.dev.",
    refs: "npm + OSV.dev",
  },
  {
    id: "07",
    name: "supply-chain",
    desc: "Typosquatting (Damerau-Levenshtein vs popular registries), install-hook abuse in package.json scripts and Python setup.py / pyproject.",
    refs: "npm + PyPI",
  },
  {
    id: "08",
    name: "ci-iac",
    desc: "Dockerfile (root user, :latest tags, ADD-from-URL, secrets in ENV) and GitHub Actions (pull_request_target checkouts, unpinned actions, write-all permissions).",
    refs: "CWE-tagged",
  },
  {
    id: "09",
    name: "posture + iam",
    desc: "Repo posture (A+ to F grade — branch protection, CODEOWNERS, signed commits, Dependabot) plus an IAM-risk lens built by a 10-year IAM/IGA specialist: org MFA enforcement, outside-collaborator permission levels, admin-equivalent privilege paths, stale-owner authorship signals. The slice of enterprise IAM tooling solo devs have never had.",
    refs: "IAM-grade",
  },
];

const FAQ: Array<{ q: string; a: string }> = [
  {
    q: "Do you store my source code?",
    a: "No. We fetch files from the GitHub API only during a scan and discard them immediately after. We persist findings (path, line, masked preview) — never the code itself.",
  },
  {
    q: "What permissions does TriageRook need?",
    a: "Sign-in is via the TriageRook Security GitHub App and gives us read access to your public repositories. We do not read private code. The optional auto-fix PR feature requires you to install the App on the target repo — that grants Contents: write and Pull requests: write scoped to that single repo, used only to open a PR you then review.",
  },
  {
    q: "Can I scan private repositories?",
    a: "Not yet. Sign-in today gives TriageRook read access to your public repositories only. Private-repo support is on the roadmap.",
  },
  {
    q: "How is this different from GitHub secret scanning?",
    a: "GitHub's built-in scanning is free but limited to partner secret patterns. TriageRook adds 60+ curated regex patterns, an entropy fallback for custom formats, SAST rules, IaC checks for Dockerfile and GitHub Actions, supply-chain heuristics (typosquatting, install-hook abuse), a 30-commit history replay, a posture grade, and an IAM-risk lens built by a 10-year IAM specialist. One screen, severity-ranked.",
  },
  {
    q: "Does it catch insecure code generated by Copilot / Cursor / Claude?",
    a: "Partly. The SAST detector flags patterns AI assistants commonly emit: TLS verification disabled (rejectUnauthorized: false / verify=False), session cookies with httpOnly: false, bcrypt rounds below 10, process.env fallbacks to a hardcoded secret-shaped literal, and NEXT_PUBLIC_*SECRET* env reads (which Next.js inlines into the client bundle). New rules added as patterns become visible.",
  },
  {
    q: "Is TriageRook free?",
    a: "Yes, fully free during the current beta. I'm still figuring out what people value enough to pay for — feedback is very welcome.",
  },
  {
    q: "Where does my data live?",
    a: "All scan metadata is stored in Supabase, EU region. The app runs on Vercel. Both providers are SOC 2 compliant. See /security for details.",
  },
  {
    q: "What if a finding is a false positive?",
    a: "Suppress it. From the findings view you can silence a single finding (by fingerprint), a rule on a path glob, or an entire rule for the repo. Suppressions are user-scoped, persisted in Supabase, and survive across scans — no need to commit a config file. If you prefer to version-control them, a .triagerookignore at the repo root is also honored.",
  },
  {
    q: "Can I push TriageRook findings into GitHub Code Scanning?",
    a: "Yes. Every saved scan is one click from a SARIF 2.1.0 export — drop it into github/codeql-action/upload-sarif and the findings show up in your repo's Security → Code scanning tab next to CodeQL and Dependabot. Each result deep-links back to the matching rule documentation on TriageRook. Full setup at /docs/sarif.",
  },
];

const STAT_BAR: Array<{ value: string; label: string }> = [
  { value: "9", label: "detectors" },
  { value: "172", label: "rules" },
  { value: "SARIF 2.1", label: "code scanning export" },
  { value: "<60s", label: "scan time" },
  { value: "EU", label: "data region" },
  { value: "MIT", label: "license" },
];

const EXAMPLE_REPOS = [
  "vercel/next.js",
  "openai/openai-cookbook",
  "sindresorhus/awesome",
];

export default async function Home() {
  const session = await auth();
  if (session) redirect("/dashboard");

  return (
    <main className="relative min-h-screen bg-slate-950 text-slate-100 overflow-hidden">
      {/* background grid */}
      <div
        aria-hidden
        className="pointer-events-none fixed inset-0 [background-image:radial-gradient(rgba(148,163,184,0.08)_1px,transparent_1px)] [background-size:24px_24px] [mask-image:radial-gradient(ellipse_at_top,black_30%,transparent_75%)]"
      />
      {/* amber accent glow, top-right */}
      <div
        aria-hidden
        className="pointer-events-none absolute -top-40 -right-40 w-[28rem] h-[28rem] rounded-full bg-amber-400/[0.05] blur-3xl"
      />

      <div className="relative">
        {/* NAV */}
        <nav className="border-b border-slate-800/60 bg-slate-950/80 backdrop-blur sticky top-0 z-50">
          <div className="max-w-6xl mx-auto px-6 h-14 flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2 group">
              <Image
                src="/logo.png"
                alt=""
                width={28}
                height={28}
                priority
                className="shrink-0"
              />
              <span className="font-mono text-sm tracking-tight text-slate-100 group-hover:text-amber-400 transition">
                triagerook
              </span>
            </Link>
            <div className="flex items-center gap-7 text-xs font-mono text-slate-400">
              <a
                href="#detectors"
                className="hidden sm:inline hover:text-slate-100 transition"
              >
                detectors
              </a>
              <Link
                href="/docs/rules"
                className="hidden sm:inline hover:text-slate-100 transition"
              >
                rules
              </Link>
              <a
                href="#faq"
                className="hidden sm:inline hover:text-slate-100 transition"
              >
                faq
              </a>
              <Link
                href="/pricing"
                className="hidden md:inline hover:text-slate-100 transition"
              >
                pricing
              </Link>
              <Link
                href="/about"
                className="hidden md:inline hover:text-slate-100 transition"
              >
                about
              </Link>
              <Link
                href="/security"
                className="hidden md:inline hover:text-slate-100 transition"
              >
                security
              </Link>
              <a
                href="https://github.com/silviooerudon/triagerook"
                target="_blank"
                rel="noopener noreferrer"
                className="hidden md:inline hover:text-slate-100 transition"
              >
                github ↗
              </a>
              <Link
                href="/signin"
                className="px-3 py-1.5 border border-amber-400/40 text-amber-300 hover:bg-amber-400 hover:text-slate-950 transition"
              >
                sign in
              </Link>
            </div>
          </div>
        </nav>

        {/* HERO */}
        <section className="max-w-6xl mx-auto px-6 pt-20 md:pt-28 pb-20">
          <div className="grid md:grid-cols-12 gap-8">
            <div className="md:col-span-8">
              <div className="font-mono text-xs text-amber-400 mb-8 flex items-center gap-2.5">
                <span className="inline-block w-1.5 h-1.5 bg-amber-400 animate-pulse" />
                v0.9 · free during beta · no card required
              </div>
              <h1 className="font-display text-5xl md:text-7xl font-bold tracking-tight leading-[0.95] mb-8 text-balance">
                see what
                <br />
                you <span className="text-amber-400">committed.</span>
              </h1>
              <p className="text-slate-400 text-lg max-w-2xl mb-10 leading-relaxed">
                <span className="text-slate-100">
                  Security triage for solo devs.
                </span>{" "}
                Scan your GitHub repo in one click — TriageRook runs nine
                detectors against{" "}
                <span className="text-slate-100">exposed secrets</span>,{" "}
                <span className="text-slate-100">vulnerable dependencies</span>,{" "}
                <span className="text-slate-100">IaC misconfigs</span>, and the{" "}
                <span className="text-slate-100">
                  insecure patterns your AI assistant just generated
                </span>
                . Results in under sixty seconds.
              </p>
              <PublicScanInput />
              <div className="mt-4 flex items-center gap-x-3 gap-y-2 text-xs font-mono text-slate-500 flex-wrap">
                <span className="text-slate-600">try:</span>
                {EXAMPLE_REPOS.map((repo) => (
                  <Link
                    key={repo}
                    href={`/scan-public/${repo}`}
                    className="text-slate-400 hover:text-amber-400 transition border-b border-dashed border-slate-700 hover:border-amber-400"
                  >
                    {repo}
                  </Link>
                ))}
              </div>
              <div className="mt-10">
                <Link
                  href="/signin"
                  className="text-xs font-mono text-slate-500 hover:text-amber-400 transition inline-flex items-center gap-1.5"
                >
                  → or sign in with github for unlimited scans
                </Link>
              </div>
            </div>
            <div className="md:col-span-4 hidden md:block relative">
              <div
                aria-hidden
                className="font-display text-[12rem] leading-none font-bold text-slate-900 select-none absolute right-0 top-0"
              >
                60+
              </div>
              <div
                aria-hidden
                className="absolute right-0 top-[10rem] font-mono text-xs text-slate-600 text-right leading-relaxed"
              >
                secret patterns
                <br />
                in production
                <br />
                <span className="text-amber-400/80">{"// always growing"}</span>
              </div>
            </div>
          </div>
        </section>

        {/* STAT BAR */}
        <section className="border-y border-slate-800/60 bg-slate-900/30">
          <div className="max-w-6xl mx-auto px-6 py-5 flex flex-wrap items-center gap-x-8 gap-y-3 font-mono text-xs uppercase tracking-wider">
            {STAT_BAR.map((stat) => (
              <div key={stat.label} className="flex items-baseline gap-2">
                <span className="text-amber-400 text-base">{stat.value}</span>
                <span className="text-slate-500">{stat.label}</span>
              </div>
            ))}
          </div>
        </section>

        {/* EXAMPLE OUTPUT */}
        <section className="max-w-6xl mx-auto px-6 py-24">
          <div className="grid md:grid-cols-12 gap-10 items-start">
            <div className="md:col-span-4">
              <div className="font-mono text-xs text-amber-400 mb-3">
                {"// example output"}
              </div>
              <h2 className="font-display text-3xl md:text-4xl font-bold tracking-tight mb-5 leading-tight">
                what a real scan looks like.
              </h2>
              <p className="text-slate-400 text-sm leading-relaxed">
                Findings come back grouped by severity, with a file path, line
                number, and a masked preview. No 800-page PDF. No upsell to
                enterprise.
              </p>
            </div>
            <div className="md:col-span-8">
              <Terminal />
            </div>
          </div>
        </section>

        {/* DETECTORS */}
        <section id="detectors" className="border-t border-slate-800/60">
          <div className="max-w-6xl mx-auto px-6 py-24">
            <div className="grid md:grid-cols-12 gap-10 mb-12">
              <div className="md:col-span-5">
                <div className="font-mono text-xs text-amber-400 mb-3">
                  {"// detectors"}
                </div>
                <h2 className="font-display text-3xl md:text-4xl font-bold tracking-tight leading-tight">
                  nine detectors,
                  <br />
                  run in parallel.
                </h2>
              </div>
              <div className="md:col-span-7 flex items-end">
                <p className="text-slate-400 leading-relaxed">
                  Each scan runs every detector against your repo concurrently.
                  No setup, no config files, no allowlist tuning — just sane
                  defaults that flag what an attacker would actually find.
                </p>
              </div>
            </div>
            <div className="border border-slate-800 divide-y divide-slate-800/60 rounded-lg overflow-hidden">
              {DETECTORS.map((d) => (
                <DetectorRow key={d.id} {...d} />
              ))}
            </div>
            <p className="text-center text-xs font-mono text-slate-600 mt-10">
              {"// more detectors added based on what users actually leak"}
            </p>
          </div>
        </section>

        {/* BEYOND DETECTION */}
        <section className="border-t border-slate-800/60">
          <div className="max-w-6xl mx-auto px-6 py-24">
            <div className="grid md:grid-cols-12 gap-10 mb-12">
              <div className="md:col-span-5">
                <div className="font-mono text-xs text-amber-400 mb-3">
                  {"// beyond detection"}
                </div>
                <h2 className="font-display text-3xl md:text-4xl font-bold tracking-tight leading-tight">
                  detect, then
                  <br />
                  actually fix it.
                </h2>
              </div>
              <div className="md:col-span-7 flex items-end">
                <p className="text-slate-400 leading-relaxed">
                  A finding you can&apos;t act on is just noise. Every scan ships
                  with the rails to move from &quot;here&apos;s what&apos;s wrong&quot;
                  to &quot;here&apos;s the PR that fixes it&quot; — or, when it&apos;s a
                  false positive, to make it stop nagging you.
                </p>
              </div>
            </div>
            <div className="grid md:grid-cols-3 gap-px bg-slate-800/40 border border-slate-800/40 rounded-lg overflow-hidden">
              <BeyondCard
                title="sarif 2.1 export"
                desc="Every saved scan is one click from a SARIF 2.1.0 export — drop it into github/codeql-action/upload-sarif and findings show up in your repo's Security → Code scanning tab next to CodeQL and Dependabot. Each rule deep-links back to its docs."
                cta={{ label: "→ setup guide", href: "/docs/sarif" }}
              />
              <BeyondCard
                title="auto-fix prs"
                desc="For findings with a clean fix (dependency bumps, secret extraction to process.env / os.environ), TriageRook opens a PR against your repo directly. Per-finding opt-in, isolated branch, preview before submit. You review before merging."
                cta={{ label: "→ how it works", href: "/security" }}
              />
              <BeyondCard
                title="suppressions"
                desc="False positives happen. Suppress a single finding (by fingerprint), a rule on a path (by glob), or a whole rule for the repo — all from the findings view. User-scoped, synced via Supabase, survives across scans. .triagerookignore in your repo also honored."
              />
            </div>
          </div>
        </section>

        {/* WHY */}
        <section className="border-t border-slate-800/60 bg-slate-900/20">
          <div className="max-w-6xl mx-auto px-6 py-24">
            <div className="font-mono text-xs text-amber-400 mb-3">
              {"// why triagerook"}
            </div>
            <h2 className="font-display text-3xl md:text-4xl font-bold tracking-tight mb-12 leading-tight">
              built for the dev who skips snyk.
            </h2>
            <div className="grid md:grid-cols-3 gap-px bg-slate-800/40 border border-slate-800/40 rounded-lg overflow-hidden">
              <WhyCard
                title="fast"
                desc="Sign in with GitHub, pick a repo, get findings. No CLI, no pipeline, no config. Most scans finish in under a minute."
              />
              <WhyCard
                title="private"
                desc="We never store your source code. Only metadata, file paths, and masked previews. All in EU region. Open source — audit it."
              />
              <WhyCard
                title="yours"
                desc="No upsell to enterprise. No mandatory SSO. No usage gating during beta. The scan you'd actually run."
              />
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section id="faq" className="border-t border-slate-800/60">
          <div className="max-w-3xl mx-auto px-6 py-24">
            <div className="font-mono text-xs text-amber-400 mb-3">{"// faq"}</div>
            <h2 className="font-display text-3xl md:text-4xl font-bold tracking-tight mb-10 leading-tight">
              asked &amp; answered.
            </h2>
            <div className="border-t border-slate-800/60">
              {FAQ.map((item) => (
                <details
                  key={item.q}
                  className="group border-b border-slate-800/60"
                >
                  <summary className="cursor-pointer flex items-center justify-between gap-6 py-5 list-none">
                    <span className="font-mono text-sm text-slate-200 group-hover:text-amber-300 transition">
                      {item.q}
                    </span>
                    <span className="font-mono text-amber-400 group-open:rotate-45 transition-transform text-lg leading-none shrink-0">
                      +
                    </span>
                  </summary>
                  <p className="pb-5 pr-10 text-sm text-slate-400 leading-relaxed">
                    {item.a}
                  </p>
                </details>
              ))}
            </div>
          </div>
        </section>

        {/* FOOTER */}
        <footer className="border-t border-slate-800/60">
          <div className="max-w-6xl mx-auto px-6 py-14 font-mono text-xs">
            <div className="grid md:grid-cols-12 gap-8">
              <div className="md:col-span-7">
                <div className="flex items-center gap-2 mb-3">
                  <Image
                    src="/logo.png"
                    alt=""
                    width={20}
                    height={20}
                    className="shrink-0"
                  />
                  <span className="text-amber-400">triagerook</span>
                </div>
                <p className="text-slate-400 leading-relaxed">
                  <span className="text-slate-600">$ whoami</span>
                  <br />→ built in dublin by{" "}
                  <a
                    href="https://www.linkedin.com/in/silvio-junior-de-almeida-gazzoli-78453a8a/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-slate-200 hover:text-amber-400 transition border-b border-dashed border-slate-700 hover:border-amber-400"
                  >
                    silvio gazzoli
                  </a>
                  , iam specialist · 10+ years
                  <br />→ not affiliated with github
                </p>
              </div>
              <div className="md:col-span-5 flex md:justify-end items-start gap-x-6 gap-y-2 flex-wrap text-slate-500">
                <Link
                  href="/about"
                  className="hover:text-amber-400 transition"
                >
                  about
                </Link>
                <Link
                  href="/pricing"
                  className="hover:text-amber-400 transition"
                >
                  pricing
                </Link>
                <Link
                  href="/security"
                  className="hover:text-amber-400 transition"
                >
                  security
                </Link>
                <a
                  href="#detectors"
                  className="hover:text-amber-400 transition"
                >
                  detectors
                </a>
                <a href="#faq" className="hover:text-amber-400 transition">
                  faq
                </a>
                <a
                  href="https://github.com/silviooerudon/triagerook"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:text-amber-400 transition"
                >
                  github ↗
                </a>
              </div>
            </div>
            <div className="mt-12 pt-6 border-t border-slate-800/40 flex justify-between items-center text-slate-600 flex-wrap gap-2">
              <span>triagerook © {new Date().getFullYear()}</span>
              <span className="flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                mit license · open source
              </span>
            </div>
          </div>
        </footer>
      </div>
    </main>
  );
}

function DetectorRow({
  id,
  name,
  desc,
  refs,
}: {
  id: string;
  name: string;
  desc: string;
  refs: string;
}) {
  return (
    <div className="grid md:grid-cols-12 gap-2 md:gap-4 px-5 py-4 hover:bg-slate-900/40 transition">
      <div className="md:col-span-1 font-mono text-xs text-slate-600">{id}</div>
      <div className="md:col-span-3 font-mono text-sm text-amber-300">
        {name}
      </div>
      <div className="md:col-span-6 text-sm text-slate-300 leading-relaxed">
        {desc}
      </div>
      <div className="md:col-span-2 font-mono text-xs text-slate-500 md:text-right">
        {refs}
      </div>
    </div>
  );
}

function WhyCard({ title, desc }: { title: string; desc: string }) {
  return (
    <div className="bg-slate-950 p-7">
      <div className="font-mono text-amber-400 text-xs mb-3 tracking-wider">
        ## {title}
      </div>
      <p className="text-slate-300 leading-relaxed">{desc}</p>
    </div>
  );
}

function BeyondCard({
  title,
  desc,
  cta,
}: {
  title: string;
  desc: string;
  cta?: { label: string; href: string };
}) {
  return (
    <div className="bg-slate-950 p-7 flex flex-col">
      <div className="font-mono text-amber-400 text-xs mb-3 tracking-wider">
        ## {title}
      </div>
      <p className="text-slate-300 leading-relaxed text-sm flex-1">{desc}</p>
      {cta && (
        <Link
          href={cta.href}
          className="mt-5 font-mono text-xs text-slate-400 hover:text-amber-400 transition border-b border-dashed border-slate-700 hover:border-amber-400 self-start"
        >
          {cta.label}
        </Link>
      )}
    </div>
  );
}

function Terminal() {
  return (
    <div className="border border-slate-800 rounded-lg overflow-hidden bg-slate-950 shadow-2xl shadow-amber-400/[0.04]">
      <div className="bg-slate-900 px-4 py-2.5 border-b border-slate-800 flex items-center gap-2">
        <span className="w-2.5 h-2.5 rounded-full bg-slate-700" />
        <span className="w-2.5 h-2.5 rounded-full bg-slate-700" />
        <span className="w-2.5 h-2.5 rounded-full bg-slate-700" />
        <span className="ml-2 font-mono text-xs text-slate-500">
          triagerook — scan
        </span>
      </div>
      <div className="p-5 font-mono text-xs leading-relaxed">
        <div className="text-slate-500">
          <span className="text-amber-400">$</span>{" "}
          <span className="text-slate-200">
            triagerook scan vercel/next.js
          </span>
        </div>
        <div className="mt-4 space-y-1 text-slate-400">
          <div>┌─ summary ────────────────────────────</div>
          <div>
            │ risk score{"     "}
            <span className="text-emerald-400">92 / 100</span>
            {"  "}excellent
          </div>
          <div>
            │ files scanned{"  "}
            <span className="text-slate-200">1,247</span>
          </div>
          <div>
            │ duration{"       "}
            <span className="text-slate-200">47s</span>
          </div>
          <div>└──────────────────────────────────────</div>
        </div>
        <div className="mt-4 space-y-1.5">
          <FindingLine
            sev="CRIT"
            tone="text-red-400"
            rule="aws-access-key  in commit history (3w ago)"
            path="src/seed.ts:14"
          />
          <FindingLine
            sev="HIGH"
            tone="text-orange-400"
            rule="next-public-secret-name  CWE-200"
            path="lib/db.ts:7"
          />
          <FindingLine
            sev="HIGH"
            tone="text-orange-400"
            rule="cve-2024-21501  lodash@4.17.20"
            path="package.json"
          />
          <FindingLine
            sev="HIGH"
            tone="text-orange-400"
            rule="tls-verify-disabled  CWE-295"
            path="lib/http.ts:42"
          />
          <FindingLine
            sev="MED "
            tone="text-yellow-400"
            rule="gha-pull-request-target-checkout-head"
            path=".github/workflows/ci.yml:23"
          />
          <div className="text-slate-600 pt-3">
            {"// 5 of 12 findings shown · ranked by risk score"}
          </div>
        </div>
      </div>
    </div>
  );
}

function FindingLine({
  sev,
  tone,
  rule,
  path,
}: {
  sev: string;
  tone: string;
  rule: string;
  path: string;
}) {
  return (
    <div className="flex items-center gap-3 -mx-2 px-2 py-0.5 rounded hover:bg-slate-900/50 transition">
      <span className={`${tone} font-bold whitespace-pre`}>[{sev}]</span>
      <span className="text-slate-200 flex-1 truncate">{rule}</span>
      <span className="text-slate-500 text-[11px] hidden sm:inline">
        {path}
      </span>
    </div>
  );
}
