import type { DependencyFinding, DetectorHealth } from "./types"
import { GitHubRateLimitError, parseGitHubRateLimit } from "./scan"
import { normalizeSeverity } from "./severity"
import { buildGitHubHeaders } from "./github-fetch"

// Ruby gem scanner.
//
// Parses Gemfile.lock and queries OSV's batch endpoint with ecosystem
// "RubyGems". OSV indexes rubysec/ruby-advisory-db, which is what
// bundler-audit uses — so coverage is in line with what a Ruby user
// would see locally.
//
// Why Gemfile.lock and not Gemfile:
//   - Gemfile carries version *constraints* (`gem "rails", "~> 7.0"`),
//     not pinned versions. OSV needs an exact version.
//   - Gemfile.lock is generated by `bundle install` and pins every
//     gem (direct + transitive) to a concrete version. It's the
//     authoritative source for "what's actually in this build".
//   - If a repo ships Gemfile but no Gemfile.lock, we skip — that
//     repo isn't using version locking, and reporting against the
//     constraints would give false signal.

type OsvVulnerability = {
  id: string
  summary?: string
  details?: string
  aliases?: string[]
  severity?: Array<{ type: string; score: string }>
  database_specific?: { severity?: string; cwe_ids?: string[] }
  affected?: Array<{
    package: { name: string; ecosystem: string }
    ranges?: Array<{
      type: string
      events: Array<{ introduced?: string; fixed?: string; last_affected?: string }>
    }>
    versions?: string[]
  }>
  references?: Array<{ type: string; url: string }>
}

type OsvBatchResponse = {
  results: Array<{ vulns?: Array<{ id: string }> }>
}

const OSV_BATCH_URL = "https://api.osv.dev/v1/querybatch"
const OSV_VULN_URL = "https://api.osv.dev/v1/vulns"
const MAX_PACKAGES = 500

type ParsedDep = {
  name: string
  version: string
  source: "Gemfile.lock"
}

// Parse a Gemfile.lock file. The format is line-based with a `GEM`
// section listing every gem and its version. Example:
//
//   GEM
//     remote: https://rubygems.org/
//     specs:
//       activesupport (7.0.4)
//         concurrent-ruby (~> 1.0, >= 1.0.2)
//       nokogiri (1.13.10)
//
// We only care about the top-level `name (version)` lines under
// `specs:`, where indent depth is exactly 4 spaces. Deeper-indented
// lines are transitive constraints already covered by their own
// top-level entry, so skip to avoid double-counting.
export function parseGemfileLock(content: string): ParsedDep[] {
  const deps: ParsedDep[] = []
  const lines = content.split("\n")

  let inSpecs = false
  for (const raw of lines) {
    if (raw.trim() === "specs:") {
      inSpecs = true
      continue
    }
    if (inSpecs) {
      // A blank line or a new top-level section header (`PLATFORMS`,
      // `DEPENDENCIES`, `RUBY VERSION`, etc.) ends the specs block.
      if (raw.trim() === "" || /^[A-Z]/.test(raw)) {
        inSpecs = false
        continue
      }
      // Top-level gem entries are indented with exactly 4 spaces.
      // Transitive constraints are indented 6+; skip them.
      const match = raw.match(/^ {4}([A-Za-z0-9][A-Za-z0-9._-]*) \(([0-9][A-Za-z0-9._-]*)\)\s*$/)
      if (!match) continue
      const [, name, version] = match
      deps.push({ name, version, source: "Gemfile.lock" })
    }
  }

  return deps
}

async function fetchRepoFile(
  owner: string,
  repo: string,
  path: string,
  token: string | null,
): Promise<string | null> {
  const res = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${path}`,
    {
      headers: buildGitHubHeaders(token, "application/vnd.github.v3.raw"),
      cache: "no-store",
    },
  )
  if (res.status === 404) return null
  if (!res.ok) {
    const retry = parseGitHubRateLimit(res)
    if (retry !== null) throw new GitHubRateLimitError(retry)
    return null
  }
  return res.text()
}

function mapOsvSeverity(
  vuln: OsvVulnerability,
): { severity: DependencyFinding["severity"]; cvss: number | null } {
  const cvssStr = vuln.severity?.find((s) => s.type.startsWith("CVSS"))?.score
  const cvss = cvssStr ? extractCvssScore(cvssStr) : null
  const dbSev = vuln.database_specific?.severity
  let severity: DependencyFinding["severity"] = normalizeSeverity(dbSev)
  if (!dbSev && cvss !== null) {
    if (cvss >= 9) severity = "critical"
    else if (cvss >= 7) severity = "high"
    else if (cvss >= 4) severity = "medium"
    else severity = "low"
  }
  return { severity, cvss }
}

function extractCvssScore(cvssVector: string): number | null {
  const num = Number.parseFloat(cvssVector)
  if (Number.isFinite(num)) return num
  return null
}

function buildVulnerableRange(vuln: OsvVulnerability, pkgName: string): string {
  const affected = vuln.affected?.find(
    (a) => a.package.name.toLowerCase() === pkgName.toLowerCase(),
  )
  if (!affected?.ranges?.length) return "unknown"
  const parts: string[] = []
  for (const range of affected.ranges) {
    let introduced = ""
    let fixed = ""
    for (const event of range.events) {
      if (event.introduced) introduced = event.introduced
      if (event.fixed) fixed = event.fixed
    }
    if (introduced === "0" && fixed) parts.push(`< ${fixed}`)
    else if (introduced && fixed) parts.push(`>= ${introduced}, < ${fixed}`)
    else if (introduced) parts.push(`>= ${introduced}`)
    else if (fixed) parts.push(`< ${fixed}`)
  }
  return parts.length > 0 ? parts.join(" or ") : "unknown"
}

function findGhsa(vuln: OsvVulnerability): string | null {
  if (vuln.id.startsWith("GHSA-")) return vuln.id
  return vuln.aliases?.find((a) => a.startsWith("GHSA-")) ?? null
}

function findAdvisoryUrl(vuln: OsvVulnerability): string {
  const ghsa = findGhsa(vuln)
  if (ghsa) return `https://github.com/advisories/${ghsa}`
  const ref = vuln.references?.find((r) => r.type === "ADVISORY")?.url
  if (ref) return ref
  return `https://osv.dev/vulnerability/${vuln.id}`
}

async function fetchOsvDetails(id: string): Promise<OsvVulnerability | null> {
  try {
    const res = await fetch(`${OSV_VULN_URL}/${id}`, { cache: "no-store" })
    if (!res.ok) return null
    return res.json()
  } catch {
    return null
  }
}

export type RubyDepsScanResult = {
  findings: DependencyFinding[]
  degraded: DetectorHealth | null
}

export async function scanRubyDependencies(
  owner: string,
  repo: string,
  token: string | null,
): Promise<RubyDepsScanResult> {
  const content = await fetchRepoFile(owner, repo, "Gemfile.lock", token)
  if (!content) return { findings: [], degraded: null }

  const parsed = parseGemfileLock(content)
  if (parsed.length === 0) return { findings: [], degraded: null }

  const seen = new Set<string>()
  const unique = parsed
    .filter((d) => {
      const key = `${d.name}@${d.version}`
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .slice(0, MAX_PACKAGES)

  const batchBody = {
    queries: unique.map((d) => ({
      package: { name: d.name, ecosystem: "RubyGems" },
      version: d.version,
    })),
  }

  let batchRes: Response
  try {
    batchRes = await fetch(OSV_BATCH_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(batchBody),
      cache: "no-store",
    })
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.warn("[ruby-deps] OSV batch fetch failed:", msg)
    return {
      findings: [],
      degraded: {
        detector: "osv",
        reason: `OSV.dev unreachable (${msg.slice(0, 80)}). Ruby vulnerability scan skipped.`,
      },
    }
  }
  if (!batchRes.ok) {
    return {
      findings: [],
      degraded: {
        detector: "osv",
        reason: `OSV.dev API returned ${batchRes.status}. Ruby vulnerability scan skipped.`,
      },
    }
  }
  const batchJson = (await batchRes.json()) as OsvBatchResponse

  const idToPackages = new Map<string, ParsedDep[]>()
  batchJson.results.forEach((result, idx) => {
    if (!result.vulns) return
    const pkg = unique[idx]
    for (const vuln of result.vulns) {
      if (!idToPackages.has(vuln.id)) idToPackages.set(vuln.id, [])
      idToPackages.get(vuln.id)!.push(pkg)
    }
  })

  if (idToPackages.size === 0) return { findings: [], degraded: null }

  const ids = Array.from(idToPackages.keys()).slice(0, 100)
  const details = await Promise.all(ids.map((id) => fetchOsvDetails(id)))

  const findings: DependencyFinding[] = []
  details.forEach((vuln, i) => {
    if (!vuln) return
    const pkgs = idToPackages.get(ids[i])!
    const { severity, cvss } = mapOsvSeverity(vuln)
    for (const pkg of pkgs) {
      findings.push({
        package: pkg.name,
        version: pkg.version,
        ecosystem: "RubyGems",
        severity,
        title: vuln.summary ?? vuln.id,
        ghsa: findGhsa(vuln),
        vulnerable_versions: buildVulnerableRange(vuln, pkg.name),
        cvss_score: cvss,
        url: findAdvisoryUrl(vuln),
        source: pkg.source,
      })
    }
  })

  return { findings, degraded: null }
}
