import { auth } from "@/auth"
import { NextResponse } from "next/server"
import type { PrioritizedFinding } from "@/lib/risk"
import { createPullRequestFromPatches } from "@/lib/octokit-app"
import { prepareFixContext, type FixContextRequestBody } from "@/lib/fix-context"

export const dynamic = "force-dynamic"

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40)
}

function timeSuffix(): string {
  const d = new Date()
  const pad = (n: number) => String(n).padStart(2, "0")
  return `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}-${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}`
}

export async function POST(request: Request) {
  const session = await auth()
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  let body: FixContextRequestBody
  try {
    body = (await request.json()) as FixContextRequestBody
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 })
  }

  const outcome = await prepareFixContext(session, body, "fix")
  if (!outcome.ok) {
    return NextResponse.json(
      { error: outcome.error, code: outcome.code },
      { status: outcome.status },
    )
  }

  const { token, owner, repo, finding, defaultBranch, engineResult } = outcome.ctx

  const slug = slugify(engineResult.summary)
  const branchName = `repoguard/${engineResult.kind}-${slug}-${timeSuffix()}`

  const commitMessage = engineResult.summary
  const prTitle = engineResult.summary
  const prBody = buildPrBody(engineResult.kind, finding, engineResult.summary)

  try {
    const pr = await createPullRequestFromPatches(token, {
      owner,
      repo,
      baseBranch: defaultBranch,
      newBranch: branchName,
      commitMessage,
      prTitle,
      prBody,
      patches: engineResult.patches,
    })

    return NextResponse.json({
      kind: engineResult.kind,
      summary: engineResult.summary,
      prUrl: pr.url,
      prNumber: pr.number,
      branch: branchName,
    })
  } catch (err) {
    console.error("[fix] Failed to create PR:", err)
    const message = err instanceof Error ? err.message : "PR creation failed"
    return NextResponse.json({ error: message }, { status: 502 })
  }
}

function buildPrBody(
  kind: string,
  finding: PrioritizedFinding,
  summary: string
): string {
  const lines = [
    "Automated fix proposed by RepoGuard.",
    "",
    `**Fix:** ${summary}`,
    `**Kind:** \`${kind}\``,
    "",
    "## Finding",
    "",
  ]

  if (finding.kind === "dependency") {
    const d = finding.data
    lines.push(`- Package: \`${d.package}@${d.version}\``)
    lines.push(`- Severity: ${d.severity}`)
    if (d.ghsa) lines.push(`- Advisory: ${d.ghsa}`)
    lines.push(`- Vulnerable versions: \`${d.vulnerable_versions}\``)
    if (d.url) lines.push(`- Details: ${d.url}`)
  } else if (finding.kind === "secret") {
    const d = finding.data
    lines.push(`- Pattern: ${d.patternName}`)
    lines.push(`- Severity: ${d.severity}`)
    lines.push(`- Location: \`${d.filePath}:${d.lineNumber}\``)
  } else if (finding.kind === "code") {
    const d = finding.data
    lines.push(`- Rule: ${d.ruleName}`)
    lines.push(`- Severity: ${d.severity}`)
    lines.push(`- Location: \`${d.filePath}:${d.lineNumber}\``)
    if (d.cwe) lines.push(`- CWE: ${d.cwe}`)
  }

  lines.push("")
  lines.push("## Before merging")
  lines.push("")
  lines.push("- Review the diff manually.")
  lines.push("- Make sure your CI / tests pass on this branch.")

  if (kind === "dep-bump") {
    lines.push("- Run your package manager install command locally to refresh the lockfile.")
  }
  if (kind === "secret-extract") {
    lines.push("- Set the new env var in your deployment (Vercel, etc).")
    lines.push("- Rotate the leaked secret — extracting to env does not invalidate the old value.")
  }

  lines.push("")
  lines.push("Generated by RepoGuard.")
  return lines.join("\n")
}
