// scripts/refresh-popular-packages.ts
//
// ============================================================================
// STATUS (validated 2026-05-07): refresh URLs are BEST-EFFORT.
//
// Upon validation in E2.1, both npm sources returned 404:
//   - https://github.com/LeoDog896/npm-rank/releases/latest/download/raw.json
//   - https://github.com/tristan-f-r/npm-rank/releases/latest/download/raw.json
//     (LeoDog896/npm-rank was renamed to tristan-f-r/npm-rank, but neither
//      has a stable `latest/download/raw.json` release asset as of 2026-05.)
//
// PyPI source could not be validated from the build environment but is
// believed to still be active.
//
// SOURCE OF TRUTH for typosquatting detection: lib/data/popular-*.json
// The seed lists (top 100 npm + top 80 PyPI) cover all historically
// documented typosquat targets (lodash, express, react, axios, requests,
// urllib3, numpy, pyyaml, cryptography, etc).
//
// When refresh is needed (e.g. customer reports typosquat of pkg outside seed):
//   Option A: switch npm source to `npm-high-impact` package
//             npm install --save-dev npm-high-impact
//             import { npmTopDownloads } from "npm-high-impact"
//   Option B: expand seed lists manually (no external dep)
//   Option C: use ecosyste.ms API or npms.io paginated search
//
// Until then, this script may fail. That is expected and not a regression.
// ============================================================================
//
// Run: npx tsx scripts/refresh-popular-packages.ts

import { writeFile } from "node:fs/promises";
import { join } from "node:path";

const NPM_TOP_URL =
  "https://github.com/tristan-f-r/npm-rank/releases/latest/download/raw.json";

const PYPI_TOP_URL =
  "https://hugovk.github.io/top-pypi-packages/top-pypi-packages.min.json";

const NPM_LIMIT = 5000;
const PYPI_LIMIT = 1000;

const OUT_DIR = join(process.cwd(), "lib", "data");

interface OutputPackage {
  name: string;
  rank: number;
}

interface OutputFile {
  meta: {
    ecosystem: string;
    source: string;
    generatedAt: string;
    count: number;
    note: string;
  };
  packages: OutputPackage[];
}

async function fetchJson(url: string): Promise<unknown> {
  const res = await fetch(url, {
    redirect: "follow",
    headers: { "User-Agent": "TriageRook refresh-popular-packages" },
  });
  if (!res.ok) {
    throw new Error(`Fetch failed: ${url} -> ${res.status} ${res.statusText}`);
  }
  return res.json();
}

async function refreshNpm(): Promise<void> {
  console.log(`[npm] Fetching from ${NPM_TOP_URL}`);
  const raw = (await fetchJson(NPM_TOP_URL)) as Array<{ name?: string }>;

  if (!Array.isArray(raw)) {
    throw new Error("npm fetch did not return an array");
  }

  const packages: OutputPackage[] = [];
  for (let i = 0; i < raw.length && packages.length < NPM_LIMIT; i++) {
    const item = raw[i];
    if (item && typeof item.name === "string" && item.name.length > 0) {
      packages.push({ name: item.name, rank: packages.length + 1 });
    }
  }

  const out: OutputFile = {
    meta: {
      ecosystem: "npm",
      source: NPM_TOP_URL,
      generatedAt: new Date().toISOString(),
      count: packages.length,
      note: "Auto-generated by scripts/refresh-popular-packages.ts. Do not edit by hand.",
    },
    packages,
  };

  const path = join(OUT_DIR, "popular-npm.json");
  await writeFile(path, JSON.stringify(out, null, 2) + "\n", "utf-8");
  console.log(`[npm] Wrote ${packages.length} packages to ${path}`);
}

async function refreshPyPI(): Promise<void> {
  console.log(`[pypi] Fetching from ${PYPI_TOP_URL}`);
  const raw = (await fetchJson(PYPI_TOP_URL)) as {
    rows?: Array<{ project?: string; download_count?: number }>;
  };

  if (!raw || !Array.isArray(raw.rows)) {
    throw new Error("pypi fetch did not return expected { rows: [...] } shape");
  }

  const packages: OutputPackage[] = [];
  for (let i = 0; i < raw.rows.length && packages.length < PYPI_LIMIT; i++) {
    const row = raw.rows[i];
    if (row && typeof row.project === "string" && row.project.length > 0) {
      packages.push({ name: row.project, rank: packages.length + 1 });
    }
  }

  const out: OutputFile = {
    meta: {
      ecosystem: "pypi",
      source: PYPI_TOP_URL,
      generatedAt: new Date().toISOString(),
      count: packages.length,
      note: "Auto-generated by scripts/refresh-popular-packages.ts. Do not edit by hand.",
    },
    packages,
  };

  const path = join(OUT_DIR, "popular-pypi.json");
  await writeFile(path, JSON.stringify(out, null, 2) + "\n", "utf-8");
  console.log(`[pypi] Wrote ${packages.length} packages to ${path}`);
}

async function main(): Promise<void> {
  console.log("Refreshing popular package lists...");
  console.log("(See script header for status of upstream URLs.)");
  console.log("");

  let npmOk = false;
  let pypiOk = false;

  try {
    await refreshNpm();
    npmOk = true;
  } catch (err) {
    console.error("[npm] FAILED:", err instanceof Error ? err.message : err);
    console.error(
      "[npm] Seed list lib/data/popular-npm.json remains source of truth.",
    );
  }

  try {
    await refreshPyPI();
    pypiOk = true;
  } catch (err) {
    console.error("[pypi] FAILED:", err instanceof Error ? err.message : err);
    console.error(
      "[pypi] Seed list lib/data/popular-pypi.json remains source of truth.",
    );
  }

  console.log("");
  if (npmOk && pypiOk) {
    console.log("Done. Both lists refreshed.");
    process.exit(0);
  } else if (npmOk || pypiOk) {
    console.log(
      `Partial refresh: npm=${npmOk ? "ok" : "failed"}, pypi=${pypiOk ? "ok" : "failed"}.`,
    );
    process.exit(0);
  } else {
    console.error(
      "Refresh failed for both ecosystems. Seed lists remain source of truth.",
    );
    process.exit(1);
  }
}

main().catch((err) => {
  console.error("Refresh script error:", err);
  process.exit(1);
});
